spring:
  jpa:
    defer-datasource-initialization: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:db
    username: sa
    password:
    hikari:
      auto-commit: false
    NON_KEYWORDS: OFFSET
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        trace: true